language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

# pull lfs files, by first installing git-lfs
# special thanks to
# http://stackoverflow.com/questions/32580821/how-can-i-customize-override-the-git-clone-step-in-travis-ci
# https://developer.atlassian.com/blog/2016/04/git-lfs-12-clone-faster/
# https://github.com/github/git-lfs/blob/master/INSTALLING.md
sudo: required
install:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs
  - git lfs clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
